#!/usr/bin/env sh

set -e
set -o pipefail

DOCKER_SOCK=${DOCKER_SOCK:-/var/run/docker.sock}
CURL_TIMEOUT=${CURL_TIMEOUT:-30}

# SIGTERM-handler
term_handler() {
  exit 143; # 128 + 15 -- SIGTERM
}

docker_curl() {
  curl --max-time "${CURL_TIMEOUT}" --no-buffer -s --unix-socket "${DOCKER_SOCK}" "$@" || return 1
  return 0
}

trap 'kill ${!}; term_handler' SIGTERM

if [ "$1" = 'healthcheck' ]; then
  docker_curl --fail http://localhost/_ping
  exit $?
fi

if [ "$1" = 'autostop' ] && [ -e ${DOCKER_SOCK} ]; then
  
  # https://docs.docker.com/engine/api/v1.25/

  # Set depends_on label
  if [ -z "$AUTOSTOP_CONTAINER_LABEL" ]; then
    AUTOSTOP_CONTAINER_LABEL="autostop.depends_on"
  fi

  AUTOSTOP_START_PERIOD=${AUTOSTOP_START_PERIOD:=0}
  echo "Monitoring containers for dependency in ${AUTOSTOP_START_PERIOD} second(s)"
  sleep ${AUTOSTOP_START_PERIOD}

  while true; do
    sleep ${AUTOSTOP_INTERVAL:=5}
    
    apiUrl="http://localhost/containers/json?filters=\{\"label\":\[\"${AUTOSTOP_CONTAINER_LABEL}\"\]\}"
    stopTimeout=".Labels[\"autostop.timeout\"] // ${AUTOSTOP_DEFAULT_STOP_TIMEOUT:-10}"
    docker_curl "$apiUrl" | \
    jq -r "foreach .[] as \$CONTAINER([];[]; \$CONTAINER | .Id, .Names[0], .Labels.\"${AUTOSTOP_CONTAINER_LABEL}\", $stopTimeout )" | \
    while read -r CONTAINER_ID && read -r CONTAINER_NAME && read -r REFCONTAINER_NAME && read -r TIMEOUT; do
        CONTAINER_SHORT_ID=${CONTAINER_ID:0:12}
        DATE=$(date +%d-%m-%Y" "%H:%M:%S)
        if [ "null" = "$CONTAINER_NAME" ]; then
          echo "$DATE Container name of ($CONTAINER_SHORT_ID) is null, which implies container does not exist - don't need to stop"
        else
          apiUrl="http://localhost/containers/json?filters=\{\"name\":\[\"${REFCONTAINER_NAME}\"\]\}"
          if [ "$(docker_curl "$apiUrl")" = "[]" ]; then
            echo "$DATE Container ${CONTAINER_NAME} ($CONTAINER_SHORT_ID) found to be dependant of missing container - Stopping container now with ${TIMEOUT}s timeout"
            docker_curl -f -XPOST "http://localhost/containers/${CONTAINER_ID}/stop?t=${TIMEOUT}" \
              || echo "$DATE Stopping container $CONTAINER_SHORT_ID failed"
          fi
        fi
    done
  done

else
  exec "$@"
fi
